name: telegram_analytics
version: 1.0.0
config-version: 2

profile: telegram_profile

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  telegram_analytics:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
