telegram_profile:
  target: {{ env_var('DBT_TARGET', 'dev') }}
  outputs:
    dev:
      type: postgres
      host: {{ env_var('POSTGRES_HOST') }}
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      port: {{ env_var('POSTGRES_PORT') | int }}
      dbname: {{ env_var('POSTGRES_DB') }}
      schema: {{ env_var('DBT_SCHEMA', 'analytics') }}
      threads: 4