services:
  db:
    image: postgres:15
    container_name: tdp_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: tdp_api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  dagster:
    build: .
    container_name: tdp_dagster
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    command: bash -lc "dagster dev -h 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  pgdata: